VIA_ENABLE = no
OLED_DRIVER_ENABLE  = no
RGBLIGHT_ENABLE = yes
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
LEADER_ENABLE = yes
CONSOLE_ENABLE = no

SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no

LTO_ENABLE = yes