#pragma once


#define TAPPING_TERM 150
#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD

#define MOUSEKEY_DELAY              0
#define MOUSEKEY_INTERVAL           2
#define MOUSEKEY_MAX_SPEED          5
#define MOUSEKEY_TIME_TO_MAX        120

#define MOUSEKEY_WHEEL_DELAY        0
#define MOUSEKEY_WHEEL_INTERVAL     250
#define MOUSEKEY_WHEEL_MAX_SPEED    30
#define MOUSEKEY_WHEEL_TIME_TO_MAX  100

#define COMBO_ALLOW_ACTION_KEYS
#define COMBO_COUNT 14
#define COMBO_TERM 45