OLED_DRIVER_ENABLE  = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
COMBO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
LEADER_ENABLE = yes
CONSOLE_ENABLE = no


SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
COMMAND_ENABLE = no
AVR_USE_MINIMAL_PRINTF = yes

LTO_ENABLE = yes
MUSIC_ENABLE = no